baseurl = "https://sakshyamsigdel.com.np"
title = "Sakshyam Sigdel | Portfolio Website"
theme = "hugo-theme-nix"
languageCode = "en-us"

[menu]
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "post"
    weight = 0
    url = "post"

[params]
  GithubID = "S-Sigdel"
  TwitterID = "sigdel__0__0"
  Name = "Sakshyam Sigdel"
  HeaderUsername = "visitor"
  HeaderHostname = "sigdel.tech"
  Email = "sakshyam.sigdel@usm.edu"
  About = "Hello, and welcome to my website. I am a person who loves maths and wizardry that can be done with computers. On this website, you can find some info about me, my socials, and my blogs. Have a great time exploring."
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
